### PR TITLE
Raise runtime error on duplicate key

### LINKED ISSUE #7: When issuing a new subscription that overrides another one, we should freak out
For example, I made the following subscription in one place:

``` ruby
subscribe_queue :metrics_events, :clear_data, bus_event_type: 'heartbeat_minutes'
```

But I had already subscribed to `heartbeat_minutes` for `metrics_events` in another place:

``` ruby
subscribe_queue :metrics_events, :create_indexes, bus_event_type: 'heartbeat_minutes'
```

Which led to the new subscription not appearing in the subscription list.  This is understandable, but it's probably better if we raise an exception when running subscriptions instead of just overriding, for clarity.

### PR DESCRIPTION
**Pull request by joeltaylor**
Fixes  #7

### CODE REVIEW

File: spec/subscription_list_spec.rb [hunk 1]
```diff
@@ -3,10 +3,12 @@
 module QueueBus
   describe SubscriptionList do
     describe ".from_redis" do
-      it "should return from attributes" do
-        mult = {"event_one" => {"class" => "MyClass", "queue_name" => "default", "key" => "event_one", "matcher" => {"bus_event_type" => "event_one"}}, 
-                "event_two" => {"class" => "MyClass", "queue_name" => "else",    "key" => "event_two", "matcher" => {"bus_event_type" => "event_two"}}}
+      let(:mult) do
+        {"event_one" => {"class" => "MyClass", "queue_name" => "default", "key" => "event_one", "matcher" => {"bus_event_type" => "event_one"}},
+         "event_two" => {"class" => "MyClass", "queue_name" => "else",    "key" => "event_two", "matcher" => {"bus_event_type" => "event_two"}}}
+      end
```
Comment (joeltaylor) [inline spec/subscription_list_spec.rb]: The test setup has two different `queue_name` values. I'm assuming that was strictly for testing that the values get set correctly and not because that's a possible scenario? From what I understand, each app gets a new `SubscriptionList` from the dispatcher.
